apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefed-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    kubefed-control-plane: controller-manager
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      kubefed-control-plane: controller-manager
  strategy: {}
  template:
    metadata:
      labels:
        kubefed-control-plane: controller-manager
    spec:
      securityContext:
        runAsUser: 1001
      serviceAccountName: kubefed-controller
      containers:
      - command:
        - /hyperfed/controller-manager
        image: "{{ .Values.global.repository }}/{{ .Values.global.image }}:{{ .Values.global.tag }}"
        imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
        name: controller-manager
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 3
        resources:
{{- if .Values.resources }}
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
      terminationGracePeriodSeconds: 10
