{{- if .Values.certificates }}
{{- range .Values.certificates }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-3"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  isCA: true
  commonName: cert-manager
  duration: {{ .duration | default "87600h" | quote }}
  secretName: {{ .secretName }}
  issuerRef:
    name: {{ .issuerRef.name }}
    kind: {{ .issuerRef.kind }}
{{- if .issuerRef.usages }}
    usages:
  {{- range .issuerRef.usages }}
    - {{ . | quote -}}
  {{- end }}
{{- end }}
{{- if .dnsNames }}
  dnsNames:
  {{- range .dnsNames }}
    - {{ . | quote -}}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
