{{- if .Values.issuers }}
{{- $namespace := .Release.Namespace }}
{{- range .Values.issuers }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ca:
    secretName: {{ .secretName }}
{{- end }}
{{- end }}
