apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: istio-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: istio-ca
  dnsNames:
  - ca.istio.io
  duration: 87600h
  organization:
  - D2iQ
  secretName: cacerts
  issuerRef:
    name: kubernetes-ca
    kind: ClusterIssuer
