apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ template "dex-controller.fullname" . }}-webhook-serving-cert
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.name }}
    heritage: {{ .Release.Service }}
spec:
  commonName: {{ template "dex-controller.fullname" . }}-webhook-service.kubeaddons.svc
  dnsNames:
  - {{ template "dex-controller.fullname" . }}-webhook-service.kubeaddons.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ template "dex-controller.fullname" . }}-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ template "dex-controller.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.name }}
    heritage: {{ .Release.Service }}
spec:
  selfSigned: {}
