prometheus-operator:
# Here goes the values from https://github.com/mesosphere/charts/tree/master/staging/prometheus-operator, which is a subchart of this chart.
thanos:
  query:
    enabled: false
  store:
    enabled: false
  compact:
    enabled: false
  bucket:
    enabled: false
